blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.blog_list, name='blog_list'),
    path('<slug:slug>/', views.blog_detail, name='blog_detail'),

]

sikshanepal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import render
from rest_framework.authtoken import views as auth_views
from . import views

urlpatterns = [
	path('admin/', admin.site.urls),
    path('', views.index_view, name ='index'),
    path('about/', views.about_view, name ='about'),
    path('course/', views.course_view, name ='course'),
    path('course-inner/', lambda request: render(request, 'course-inner.html'), name='course-inner'),
    path('subscription/', views.subscription_view, name='subscription'),
    path('checkout/', views.checkout_view, name='checkout'),

    path('api-token-auth/', auth_views.obtain_auth_token),

    path('accounts/', include('allauth.urls')),
    path('courses/', include('courses.urls')),
    path('blog/', include('blog.urls')),
    path('contactenquiry/', include('contactenquiry.urls')),
    path('subscription/', include('subscription.urls')),
    
    
	##### user related path########################## 
	path('user/', include('user.urls')),
    path('backend/', include('backend.urls')),

    #path('user_api/', include('user_api.urls')),  # Separate user API
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

subscription/urls.py
from django.urls import path
from . import views

app_name = "subscription"

urlpatterns = [
    path('plans/', views.plans_list, name='plans_list'),
    path('checkout/<str:plan_name>/', views.checkout, name='checkout'),
    path('payment-success/', views.payment_success, name='payment_success'),
    path('payment-failure/', views.payment_failure, name='payment_failure'),
]

templates/about.html
{% extends "base.html" %}
{% load static %}

{% block title %}About Us{% endblock %}

{% block content %}
        <!-- Home -->
        
        <section id="about-home">
                    <h2>About SikshaNepal /</h2>
        </section>

        <section id="about-container">
                    <div class="about-img">
                        <img src="/static/images/a.png" alt="">
                    </div>
                    <div class="about-text">
                        <h2>Welcome to SikshaNepal, Enhance your skills with best Online Courses </h2>
                        <p>You can start and finish one of those popular courses in under a day - for free! Check out the list below.. Take the course for free</p>
                        <div class="about-fe">
                            <img src="/static/images/fe1.png" alt="">
                            <div class="fe-text">
                                <h5>Unlimited Free Courses</h5>
                                <p>You can start and finish one of these popular courses in under our site.</p>
                            </div>
                        </div>
                        <div class="about-fe">
                            <img src="/static/images/fe2.png" alt="">
                            <div class="fe-text">
                                <h5>Lifetime Access</h5>
                                <p>You can start and finish one of these popular courses in under our site.</p>
                            </div>
                        </div>
                    </div>
        </section>

        <!-- trusted by -->
        <section id="trust">
            <h1>Trusted By</h1>
            <p>Replenish man having thing gathering lights yielding shall you</p>
            <div class="trust-img">
                <img src="/static/images/trust (1).png" alt="">
                <img src="/static/images/trust (2).png" alt="">
                <img src="/static/images/trust (3).png" alt="">
                <img src="/static/images/trust (4).png" alt="">
                <img src="/static/images/trust (5).png" alt="">
                <img src="/static/images/trust (6).png" alt="">
            </div>
        </section>

 

{% endblock %}

templates/base.html
{% load static %}
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>SikshaNepal</title>

	<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" />

	<link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="icon" type="image/png" href="{% static 'images/sikshanepal.png' %}">

	<link rel="stylesheet" href="{% static 'css/login.css' %}"> <!-- Specific styles for login page -->
	<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
	<script src="{% static 'js/nav.js' %}"></script>
    
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

	<!-- message here -->

    {% if messages %}
    {% for message in messages %}

    <script>
	   alert("{{ message }}");
    </script>

    {% endfor %}
    {% endif %}
</head>

<body>

{% include "header.html" %}

<main>

{% block content %}


{% endblock %}
</main>

{% include "footer.html" %}
</body>
</html>

templates/course-inner.html
{% extends "base.html" %}
{% load static %}

{% block title %}About Us{% endblock %}

{% block content %}
        <!-- Home -->
        
        <section id="about-home">
                    <h2>Enroll Our Popular Courses And Skill Up /</h2>
        </section>

        <section id="course-inner">
            <div class="overview">
                <img class="course-img" src="/static/images/c1.jpg" alt="">
                <div class="course-head">
                    <div class="c-name">
                        <h2>Javascript Beginner Courses</h2>
                        <div class="star">
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                        </div>
                        <p>Modern JavaScript from the beginning - all the way up to JS expert level!The must-have javascript resource in 2021.</p>
                    </div>
                    <span>$49.99</span>
                </div>
                <h3>Instructor</h3>
                <div class="tutor">
                    <img src="/static/images/c4.jpg" alt="">
                    <div class="tutor-det">
                        <h5>Nischal Moktan</h5>
                        <p>Web Developer At Google</p>
                    </div>
                </div>
                <hr>
                <h3>Course Overview</h3>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt iure recusandae tempore? Nisi nobis deserunt ipsam, harum alias optio sit voluptatibus porro molestiae minus nam impedit, rerum expedita? Delectus, dolor.
                Blanditiis eaque explicabo alias eos, repellat, distinctio dolorum aspernatur aut aliquid, corrupti eius dolorem eum doloremque quisquam? Et id error voluptatem explicabo tenetur harum dolores tempora nesciunt sed? Vitae, necessitatibus?
                Vel nesciunt assumenda facere quas aliquid adipisci mollitia dolorum omnis possimus, quam nisi ea, animi distinctio officiis quaerat beatae quis porro officia. Animi deleniti omnis blanditiis voluptatum. Rerum, sed laboriosam.
                Suscipit nostrum atque tempora consectetur quis aspernatur repudiandae molestias delectus, ab quisquam nisi explicabo fuga ad, neque vero! Illo cum mollitia dolore suscipit natus. Consectetur, tempore. Assumenda neque omnis accusamus.
                Quas error vero ratione modi nihil aspernatur esse consequuntur laborum, reprehenderit corporis quam natus reiciendis magni eligendi neque qui pariatur optio laudantium accusantium quae eveniet cupiditate provident dignissimos. Dolor, eligendi.</p>
                <hr>
                <h3>What you'll learn</h3>
                <div class="learn">
                    <p> <i class="far fa-check-circle"></i> Javascript from scratch - beginner to advanced</p>
                    <p> <i class="far fa-check-circle"></i> Javascript from scratch - beginner to advanced</p>
                    <p> <i class="far fa-check-circle"></i> Javascript from scratch - beginner to advanced</p>
                    <p> <i class="far fa-check-circle"></i> Javascript from scratch - beginner to advanced</p>
                    <p> <i class="far fa-check-circle"></i> Javascript from scratch - beginner to advanced</p>
                    <p> <i class="far fa-check-circle"></i> Javascript from scratch - beginner to advanced</p>
                </div>
            </div>
            <div class="enroll">
                <h3>This course includes:</h3>
                <p> <i class="far fa-video"></i> 52 hours video</p>
                    <p> <i class="far fa-newspaper"></i> 75 articles</p>
                    <p> <i class="far fa-cloud-download"></i> Downloadable resources</p>
                    <p> <i class="far fa-infinity"></i> Full lifetime access</p>
                    <p> <i class="far fa-mobile-alt"></i> Access on mobile and TV</p>
                    <p> <i class="far fa-paperclip"></i> Assignments</p>
                    <p> <i class="far fa-trophy-alt"></i> Certificate of completion</p>
                    <div class="enroll-btn">
                        <a class="blue" href="#">Enroll Courses</a>
                    </div>

            </div>
        </section>


{% endblock %}

templates/course.html
{% extends "base.html" %}
{% load static %}

{% block title %}About Us{% endblock %}

{% block content %}
        <!-- Home -->
        
        <section id="about-home">
                    <h2>Courses /</h2>
        </section>


           <!-- Courses -->

           <section id="course">
            <h1>Our Popular Courses</h1>
            <p>Replenish man having thing gathering lights yielding shall you</p>
            <div class="course-box">
                <div onclick="window.location.href='{% url "course-inner" %}';" class="courses">


                    <img src="/static/images/c1.jpg" alt="">
                    <div class="details">
                        <span>Updated 21/8/21</span>
                        <h6>Javascript Beginners Course</h6>
                        <div class="star">
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <span>(239)</span>

                        </div>
                    </div>
                    <div class="cost">
                        $49.99
                    </div>
                </div>
                <div class="courses">
                    <img src="/static/images/c2.jpg" alt="">
                    <div class="details">
                        <span>Updated 21/8/21</span>
                        <h6>Javascript Beginners Course</h6>
                        <div class="star">
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <span>(239)</span>

                        </div>
                    </div>
                    <div class="cost">
                        $49.99
                    </div>
                </div>
                <div class="courses">
                    <img src="/static/images/c3.jpg" alt="">
                    <div class="details">
                        <span>Updated 21/8/21</span>
                        <h6>Javascript Beginners Course</h6>
                        <div class="star">
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <span>(239)</span>

                        </div>
                    </div>
                    <div class="cost">
                        $49.99
                    </div>
                </div>
                <div class="courses">
                    <img src="/static/images/c4.jpg" alt="">
                    <div class="details">
                        <span>Updated 21/8/21</span>
                        <h6>Javascript Beginners Course</h6>
                        <div class="star">
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <span>(239)</span>

                        </div>
                    </div>
                    <div class="cost">
                        $49.99
                    </div>
                </div>
                <div class="courses">
                    <img src="/static/images/c5.jpg" alt="">
                    <div class="details">
                        <span>Updated 21/8/21</span>
                        <h6>Javascript Beginners Course</h6>
                        <div class="star">
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <span>(239)</span>

                        </div>
                    </div>
                    <div class="cost">
                        $49.99
                    </div>
                </div>
                <div class="courses">
                    <img src="/static/images/c6.jpg" alt="">
                    <div class="details">
                        <span>Updated 21/8/21</span>
                        <h6>Javascript Beginners Course</h6>
                        <div class="star">
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <span>(239)</span>

                        </div>
                    </div>
                    <div class="cost">
                        $49.99
                    </div>
                </div>
                <div class="courses">
                    <img src="/static/images/c1.jpg" alt="">
                    <div class="details">
                        <span>Updated 21/8/21</span>
                        <h6>Javascript Beginners Course</h6>
                        <div class="star">
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <span>(239)</span>

                        </div>
                    </div>
                    <div class="cost">
                        $49.99
                    </div>
                </div>
                <div class="courses">
                    <img src="/static/images/c2.jpg" alt="">
                    <div class="details">
                        <span>Updated 21/8/21</span>
                        <h6>Javascript Beginners Course</h6>
                        <div class="star">
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <span>(239)</span>

                        </div>
                    </div>
                    <div class="cost">
                        $49.99
                    </div>
                </div>
                <div class="courses">
                    <img src="/static/images/c2.jpg" alt="">
                    <div class="details">
                        <span>Updated 21/8/21</span>
                        <h6>Javascript Beginners Course</h6>
                        <div class="star">
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <span>(239)</span>

                        </div>
                    </div>
                    <div class="cost">
                        $49.99
                    </div>
                </div>
                <div class="courses">
                    <img src="/static/images/c2.jpg" alt="">
                    <div class="details">
                        <span>Updated 21/8/21</span>
                        <h6>Javascript Beginners Course</h6>
                        <div class="star">
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <span>(239)</span>

                        </div>
                    </div>
                    <div class="cost">
                        $49.99
                    </div>
                </div>
            </div>
        </section>


{% endblock %} 

templates/footer.html
<!-- Footer -->
<footer>
	<div class="footer-col">
		<h3>Top Products</h3>
		<li>Online Courses</li>
        <li>Live Workshops</li>
        <li>Study Materials</li>
        <li>Certification Programs</li>
	</div>
	<div class="footer-col">
		<h3>Quick Links</h3>
		<li>Home</li>
        <li>Courses</li>
        <li>About Us</li>
        <li>Contact Us</li>
        <li>FAQ</li>
        <li>Student Dashboard</li>
	</div>
	<div class="footer-col">
		<h3>Features</h3>
		<li>Personalized Learning Paths</li>
        <li>Expert Tutors</li>
        <li>Interactive Quizzes</li>
        <li>Progress Tracking</li>
        <li>Mobile App Access</li>
	</div>
	<div class="footer-col">
		<h3>Guides</h3>
		<li>How to Enroll</li>
        <li>Study Tips & Tricks</li>
        <li>Career Advice</li>
        <li>Scholarship Information</li>
        <li>Community Forums</li>
	</div>
	<div class="footer-col">
		<h3>Newsletter</h3>
		<p>You can trust us. We only send promo offers.</p>
		<div class="subscribe">
			<input type="text" placeholder="Your Email Address">
			<a href="#" class=" yellow">SUBSCRIBE</a>
		</div>
	</div>

	<div class="copyright">
		<p>Copyright 2021 All rights reserved | SikshaNepal</p>
		<div class="pro-links">
			<i class="fab fa-facebook"></i>
			<i class="fab fa-instagram"></i>
			<i class="fab fa-linkedin-in"></i>
		</div>
	</div>
</footer>

templates/header.html
{% load static %}
<nav>
	<li class="{% if request.path == '/' %} active {% endif %}" style="list-style: none;">
				<a href="{% url 'index' %}">
					<img src="/static/images/sikshanepal.png" alt="sikshanepal">
				</a>
	</li>
	
	<div class="navigation">
		<ul>
			<i id="menu-close" class="fas fa-times"></i>

			<li class="{% if request.path == '/' %} active {% endif %}">
				<a href="{% url 'index' %}">Home</a>
			</li>
			<li class="{% if '/about/' in request.path %} active {% endif %}">
				<a href="{% url 'about' %}">About</a>
			</li>
			<li class="{% if '/blog/' in request.path %} active {% endif %}">
				<a href="{% url 'blog_list' %}">Blog</a>
			</li>
			<li class="{% if '/courses/' in request.path %} active {% endif %}">
				<a href="{% url 'course-list' %}">Courses</a>
			</li>
			<li class="{% if '/contact/' in request.path %} active {% endif %}">
				<a href="{% url 'contact' %}">Contact</a>
			</li>
			<li class="{% if '/subscription/' in request.path %} active {% endif %}">
				<a href="{% url 'subscription:plans_list' %}">Subscription</a>
			</li>
			
            


{% if user.is_authenticated %}
  <li><a href="{% url 'logout' %}">LogOut</a></li>
  
  <li class="nav-item">
    <a class="nav-link d-flex align-items-center" href="{% url 'user-profile' %}" style="gap: 0.5rem;">
      {% if user.profile_picture %}
        <img 
          src="{{ user.profile_picture.url }}" 
          alt="Profile Picture" 
          style="width: 48px; height: 48px; border-radius: 50%; object-fit: cover; border: 1px solid #ccc;"
          loading="lazy"
        >
      {% else %}
        <img 
          src="{% static 'images/default_profile.jpg' %}" 
          alt="Default Profile Picture" 
          style="width: 48px; height: 48px; border-radius: 50%; object-fit: cover; border: 1px solid #ccc;"
          loading="lazy"
        >
      {% endif %}
    </a>
  </li>
{% else %}
  <li><a href="{% url 'login' %}">Login</a></li>
  <li><a href="{% url 'register' %}">Sign Up</a></li>
{% endif %}



		</ul>
		<img id="menu-btn" src="/static/images/menu.png" alt="">
	</div>
</nav>

templates/index.html
{% extends "base.html" %}

{% block title %}Home - My Website{% endblock %}

{% block content %}

<!-- Home -->


<section id="home">
	{% if user.is_authenticated %}
	<h2>Welcome , {{ user.username }}! Empower Your Future with SikshaNepal</h2>
	<p>
		Unlock your potential with cutting-edge education tailored for tomorrow’s tech leaders. At SikshaNepal, we’re
		committed to helping you grow through hands-on learning, expert guidance, and real-world experience. Let’s shape
		your future—one line of code at a time.
	</p>

	<div class="btn">
		<a class="blue" href="#">Learn More</a>
		<a class="yellow" href="{% url 'course-list' %}">Visit Courses</a>
	</div>
	{% else %}
	<h2>Welcome, Guest ! Empower Your Future with SikshaNepal</h2>
	<p>
		Unlock your potential with cutting-edge education tailored for tomorrow’s tech leaders. At SikshaNepal, we’re
		committed to helping you grow through hands-on learning, expert guidance, and real-world experience. Let’s shape
		your future—one line of code at a time.
	</p>
	<div class="btn">
		<a class="blue" href="#">Learn More</a>
		<a class="yellow" href="{% url 'course-list' %}">Visit Courses</a>
	</div>
	{% endif %}
</section>



<!-- Courses -->


<section id="course">
	<h1>Our Popular Courses</h1>
	<p>Courses rising rapdily in the world !</p>
	<div class="course-box">
		<div class="courses">
			<img src="/static/images/bsccsit.jpg" alt="">
			<div class="details">
				<span>Updated 21/8/21</span>
				<h6>Bsc-csit</h6>
				<div class="star">
					<i class="fas fa-star"></i>
					<i class="fas fa-star"></i>
					<i class="fas fa-star"></i>
					<i class="fas fa-star"></i>
					<i class="fas fa-star"></i>
					<span>(390)</span>

				</div>
			</div>
			<div class="cost">
				FREE
			</div>
		</div>
		<div class="courses">
			<img src="/static/images/bca.jpg" alt="">
			<div class="details">
				<span>Updated 21/8/21</span>
				<h6>BCA</h6>
				<div class="star">
					<i class="fas fa-star"></i>
					<i class="fas fa-star"></i>
					<i class="fas fa-star"></i>
					<i class="fas fa-star"></i>
					<i class="fas fa-star"></i>
					<span>(239)</span>

				</div>
			</div>
			<div class="cost">
				FREE
			</div>
		</div>
		<div class="courses">
			<img src="/static/images/bit.jpg" alt="">
			<div class="details">
				<span>Updated 21/8/21</span>
				<h6>BIT</h6>
				<div class="star">
					<i class="fas fa-star"></i>
					<i class="fas fa-star"></i>
					<i class="fas fa-star"></i>
					<i class="fas fa-star"></i>
					<i class="fas fa-star"></i>
					<span>(290)</span>

				</div>
			</div>
			<div class="cost">
				FREE
			</div>
		</div>
</section>

<!-- Developers -->
<section id="experts">
	<h1>Developers</h1>
	<p>A community of innovators turning ideas into reality with passion, skill, and vision.</p>
	<div class="expert-box">

		<div class="profile">
			<img src="/static/images/nischal.jpg" alt="">
			<h6>Nischal Moktan</h6>
			<p>Python & Django Expert</p>
			<div class="pro-links">
				<a href="https://github.com/Nischal-31" target="_blank">
					<i class="fab fa-github"></i>
				</a>
				<a href="https://www.instagram.com" target="_blank">
					<i class="fab fa-instagram"></i>
				</a>
				<a href="https://www.linkedin.com/in/nischal-moktan-613685295" target="_blank">
					<i class="fab fa-linkedin-in"></i>
				</a>
			</div>

		</div>
		<div class="profile">
			<img src="/static/images/bikash.jpg" alt="">
			<h6>Bikash Gosain</h6>
			<p>ASP.NET CORE Expert</p>
			<div class="pro-links">
				<a href="https://github.com/BikashGosain/BikashGosain" target="_blank">
					<i class="fab fa-github"></i>
				</a>
				<a href="https://www.instagram.com" target="_blank">
					<i class="fab fa-instagram"></i>
				</a>
				<a href="https://www.linkedin.com" target="_blank">
					<i class="fab fa-linkedin-in"></i>
				</a>
			</div>

		</div>
		<div class="profile">
			<img src="/static/images/miraj.jpg" >
			<h6>Miraj KC</h6>
			<p>React & Frontend Expert</p>
			<div class="pro-links">
				<a href="https://www.facebook.com" target="_blank">
					<i class="fab fa-github"></i>
				</a>
				<a href="https://www.instagram.com" target="_blank">
					<i class="fab fa-instagram"></i>
				</a>
				<a href="https://www.linkedin.com/in/miraj-k-c-b998152a3?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app " target="_blank">
					<i class="fab fa-linkedin-in"></i>
				</a>
			</div>

		</div>
	</div>
</section>


<!-- Contributers -->
<section id="contributers">
	<h1>Contributors</h1>
	<p>A community of supporters providing notes, resources, and guidance to help make this project possible.</p>
	<p class="text-primary fw-semibold mb-5">
      💡 Want to contribute? Share your notes, tips, or resources and join our community today!
    </p>
		<a href="{% url 'contact' %}" class="btn btn-primary btn-lg mb-5 px-5 shadow-sm rounded-pill">
      Contact Us
    </a>

	<div class="contributers-box">

		<div class="profile">
			<img src="/static/images/pro2.webp" alt="">
			<h6>Sameer KC</h6>
			<p>Notes & Resources</p>
		</div>
		<div class="profile">
			<img src="/static/images/pro2.webp" alt="">
			<h6>Suyesh Dahal</h6>
			<p>Notes & Resources</p>
		</div>
		<div class="profile">
			<img src="/static/images/pro1.webp" alt="">
			<h6>Nikika Shah</h6>
			<p>Documentation & Help</p>
		</div>
		<div class="profile">
			<img src="/static/images/pro1.webp" >
			<h6>Yukta Dhunghana</h6>
			<p>Content & Guidance</p>
		</div>
	</div>
</section>



{% endblock %}